import sys
with open('streamlit_app.py', 'r', encoding='utf-8') as f:
    c = f.read()

c = c.replace("lang = 'en'", "lang = 'tr'")
c = c.replace('"Amazon Assistant"', '"Amazon Asistan"')
c = c.replace('Customer Experience<br>', 'Müşteri Deneyimi<br>')
c = c.replace('& FAQ Advisor', 've SSS Asistanı')
c = c.replace('Search Filter', 'Arama Filtresi')
c = c.replace('"Select Category:"', '"Kategori Seçin:"')
c = c.replace('["General Questions (FAQ)", "About Products"]', '["Temel Sorular (SSS)", "Ürün Hakkında"]')
c = c.replace('"General Questions (FAQ)": "faq"', '"Temel Sorular (SSS)": "faq"')
c = c.replace('"About Products": "review"', '"Ürün Hakkında": "review"')
c = c.replace('"💡 **Tip:** Search for shipping, returns, or account operations in \'General Questions\'; and product performance in \'About Products\'."', '"💡 **İpucu:** Kargo, iade veya hesap işlemlerini \'Temel Sorular\'da; ürün performansını \'Ürün Hakkında\' seçeneğiyle aratabilirsiniz."')
c = c.replace('"Clear Chat"', '"Sohbeti Temizle"')
c = c.replace('Hello, I am', 'Merhaba, ben')
c = c.replace('How can I help you today?', 'Size nasıl yardımcı olabilirim?')
c = c.replace('"Popular Questions (FAQ)"', '"Popüler Sorular (SSS)"')
c = c.replace('"Popular Questions (Products)"', '"Popüler Sorular (Ürün Hakkında)"')
c = c.replace('"Type what you need help with..."', '"Yardıma ihtiyacınız olan konuyu yazın..."')
c = c.replace('"Please wait, scanning the database..."', '"Lütfen bekleyin, veritabanı taranıyor..."')
c = c.replace('"Database Error: "', '"Veritabanı Hatası: "')
c = c.replace('"View Sources Used"', '"Yararlanılan Kaynakları Gör"')
c = c.replace('"Sorry, I cannot access this information right now. Please try again later."', '"Üzgünüm, şu an bilgiye erişemiyorum. Lütfen daha sonra tekrar deneyin."')
c = c.replace('"System Error: "', '"Sistem Hatası: "')
c = c.replace('"How can I track my order and where is my package?"', '"Siparişimi nasıl takip edebilirim ve kargom nerede?"')
c = c.replace('"How can I return an item? What is the return period?"', '"Aldığım ürünü nasıl iade edebilirim? İade süresi kaç gün?"')
c = c.replace('"What are the benefits of Amazon Prime and how can I cancel it?"', '"Amazon Prime üyeliğinin avantajları nelerdir ve nasıl iptal edilir?"')
c = c.replace('"When will the refund for my returned item be credited to my card?"', '"İade ettiğim ürünün ücret iadesi (refund) kartıma ne zaman yansır?"')
c = c.replace('"What feature do people like the most about B000AO3L84 (Canon 430EX Flash)? Can you summarize?"', '"B000AO3L84 (Canon 430EX Flaş) ürününü alanlar en çok hangi özelliğini beğenmiş? Özetler misin?"')
c = c.replace('"What are the chronic problems users complain about the most in product B000AO3L84?"', '"B000AO3L84 kodlu üründe kullanıcıların en çok şikayet ettiği kronik sorunlar neler?"')
c = c.replace('"What are the box contents and basic technical specs of the B000AO3L84 product? Can you add an image?"', '"B000AO3L84 ürününün kutu içeriği ve temel teknik özellikleri nelerdir? Görsel de ekler misin?"')
c = c.replace('"Is the product with ASIN B000AO3L84 worth buying? Analyze the reviews and decide."', '"B000AO3L84 ASIN kodlu ürün satın alınmaya değer mi? Yorumları analiz edip bir karar ver."')

with open('streamlit_app.py', 'w', encoding='utf-8') as f:
    f.write(c)

print('Done')
